# Generated by Django 5.0.1 on 2026-07-01 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanionProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                ("languages_spoken", models.JSONField(default=list)),
                (
                    "certifications",
                    models.JSONField(
                        default=list, help_text="List of certification names"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("BIKE", "Bike"),
                            ("CAR", "Car"),
                            ("AUTO", "Auto"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("vehicle_number", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_VERIFICATION", "Pending Verification"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="PENDING_VERIFICATION",
                        max_length=25,
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BUSY", "Busy"),
                            ("OFFLINE", "Offline"),
                        ],
                        db_index=True,
                        default="OFFLINE",
                        max_length=15,
                    ),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("location_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("total_bookings_completed", models.PositiveIntegerField(default=0)),
                (
                    "ai_trust_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("bank_account_number", models.CharField(blank=True, max_length=20)),
                ("bank_ifsc", models.CharField(blank=True, max_length=15)),
                ("bank_account_name", models.CharField(blank=True, max_length=200)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Companion Profile",
                "verbose_name_plural": "Companion Profiles",
                "db_table": "companion_profiles",
            },
        ),
        migrations.CreateModel(
            name="CompanionAvailabilitySlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(help_text="0=Monday … 6=Sunday"),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "companion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="companions.companionprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability Slot",
                "db_table": "companion_availability_slots",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CompanionSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("BASIC_CARE", "Basic Care"),
                            ("MEDICAL_ASSISTANCE", "Medical Assistance"),
                            ("PHYSIOTHERAPY", "Physiotherapy"),
                            ("NURSING", "Nursing"),
                            ("ELDERLY_CARE", "Elderly Care"),
                            ("CHILD_CARE", "Child Care"),
                            ("MENTAL_HEALTH", "Mental Health Support"),
                            ("EMERGENCY", "Emergency Response"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                (
                    "proficiency_level",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="1=Beginner, 2=Intermediate, 3=Expert"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "companion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="companions.companionprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Companion Skill",
                "db_table": "companion_skills",
            },
        ),
        migrations.AddIndex(
            model_name="companionprofile",
            index=models.Index(
                fields=["status", "availability_status"],
                name="companion_p_status_b0f17c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companionprofile",
            index=models.Index(
                fields=["ai_trust_score"], name="companion_p_ai_trus_ab9118_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companionprofile",
            index=models.Index(
                fields=["average_rating"], name="companion_p_average_067e07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companionavailabilityslot",
            index=models.Index(
                fields=["companion", "day_of_week"],
                name="companion_a_compani_3f7036_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companionskill",
            unique_together={("companion", "skill")},
        ),
    ]
