# Generated by Django 5.0.1 on 2026-07-01 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("LAB_REPORT", "Lab Report"),
                            ("PRESCRIPTION", "Prescription"),
                            ("IMAGING", "Imaging / Radiology"),
                            ("DISCHARGE", "Discharge Summary"),
                            ("VACCINATION", "Vaccination"),
                            ("SURGERY", "Surgery / Procedure"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="CONSULTATION",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("hospital_name", models.CharField(blank=True, max_length=255)),
                ("doctor_name", models.CharField(blank=True, max_length=255)),
                ("doctor_specialization", models.CharField(blank=True, max_length=100)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment_notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("record_date", models.DateField(db_index=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "medical_records",
                "ordering": ["-record_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_name", models.CharField(max_length=255)),
                ("lab_name", models.CharField(blank=True, max_length=255)),
                ("test_date", models.DateField()),
                ("result_value", models.CharField(blank=True, max_length=255)),
                ("reference_range", models.CharField(blank=True, max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("ABNORMAL", "Abnormal"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_reports",
                        to="medical_records.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Report",
                "verbose_name_plural": "Lab Reports",
                "db_table": "lab_reports",
                "ordering": ["-test_date"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("ONCE_DAILY", "Once Daily"),
                            ("TWICE_DAILY", "Twice Daily"),
                            ("THRICE_DAILY", "Thrice Daily"),
                            ("FOUR_TIMES", "Four Times Daily"),
                            ("AS_NEEDED", "As Needed"),
                            ("WEEKLY", "Weekly"),
                            ("OTHER", "Other"),
                        ],
                        default="ONCE_DAILY",
                        max_length=20,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("instructions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("prescribed_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medical_records.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "db_table": "prescriptions",
                "ordering": ["-prescribed_date"],
            },
        ),
        migrations.CreateModel(
            name="RecordDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="medical_records/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("IMAGE", "Image"),
                            ("OTHER", "Other"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                ("file_size_kb", models.PositiveIntegerField(default=0)),
                ("uploaded_by", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="medical_records.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record Document",
                "verbose_name_plural": "Record Documents",
                "db_table": "record_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["patient", "is_deleted"], name="medical_rec_patient_62feb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["record_type", "record_date"],
                name="medical_rec_record__736555_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="labreport",
            index=models.Index(
                fields=["medical_record", "status"],
                name="lab_reports_medical_075ad7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["medical_record", "status"],
                name="prescriptio_medical_ef6abb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recorddocument",
            index=models.Index(
                fields=["medical_record"], name="record_docu_medical_a68691_idx"
            ),
        ),
    ]
