# Generated by Django 5.0.1 on 2026-07-01 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "inclusions",
                    models.JSONField(
                        default=list, help_text="List of included services"
                    ),
                ),
                (
                    "exclusions",
                    models.JSONField(
                        default=list, help_text="List of excluded services"
                    ),
                ),
                (
                    "min_duration_hours",
                    models.DecimalField(decimal_places=1, default=1, max_digits=4),
                ),
                (
                    "max_duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("companion_count", models.PositiveSmallIntegerField(default=1)),
                ("requires_vehicle", models.BooleanField(default=False)),
                ("requires_medical_training", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DRAFT", "Draft"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Package",
                "verbose_name_plural": "Service Packages",
                "db_table": "service_packages",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("HOSPITAL_VISIT", "Hospital Visit"),
                            ("HOME_CARE", "Home Care"),
                            ("EMERGENCY", "Emergency"),
                            ("DIAGNOSTIC", "Diagnostic"),
                            ("PHARMACY", "Pharmacy Run"),
                            ("PHYSIOTHERAPY", "Physiotherapy"),
                            ("NURSING", "Nursing"),
                        ],
                        db_index=True,
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class or URL", max_length=100
                    ),
                ),
                ("is_emergency", models.BooleanField(db_index=True, default=False)),
                ("requires_companion", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DRAFT", "Draft"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Type",
                "verbose_name_plural": "Service Types",
                "db_table": "service_types",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServicePricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("FIXED", "Fixed"),
                            ("PACKAGE", "Package"),
                        ],
                        default="HOURLY",
                        max_length=10,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Base price in INR", max_digits=10
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per-hour rate for HOURLY pricing",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "emergency_surcharge_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Emergency surcharge percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "night_surcharge_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Night-time surcharge percentage (10 PM – 6 AM)",
                        max_digits=5,
                    ),
                ),
                (
                    "platform_commission_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Platform commission percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "gst_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="GST percentage",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="services.servicepackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Pricing",
                "verbose_name_plural": "Service Pricing",
                "db_table": "service_pricing",
            },
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="services.servicetype",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepackage",
            index=models.Index(
                fields=["service_type", "status"], name="service_pac_service_c36122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicepackage",
            index=models.Index(
                fields=["is_featured"], name="service_pac_is_feat_fea8df_idx"
            ),
        ),
    ]
