# Generated by Django 5.0.1 on 2026-07-01 06:20

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(default="English", max_length=50),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("CALL", "Call"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        default="SMS",
                        max_length=20,
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
                ("premium_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Profile",
                "verbose_name_plural": "Family Profiles",
                "db_table": "family_profiles",
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("SELF", "Self"),
                            ("SPOUSE", "Spouse"),
                            ("PARENT", "Parent"),
                            ("CHILD", "Child"),
                            ("SIBLING", "Sibling"),
                            ("GRANDPARENT", "Grandparent"),
                            ("GRANDCHILD", "Grandchild"),
                            ("UNCLE_AUNT", "Uncle / Aunt"),
                            ("NEPHEW_NIECE", "Nephew / Niece"),
                            ("FRIEND", "Friend"),
                            ("CAREGIVER", "Caregiver"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="family/members/%Y/%m/"
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("known_allergies", models.TextField(blank=True)),
                ("chronic_conditions", models.TextField(blank=True)),
                (
                    "is_primary_patient",
                    models.BooleanField(
                        default=False,
                        help_text="Marks the main patient for this family account.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="family.familyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Member",
                "verbose_name_plural": "Family Members",
                "db_table": "family_members",
                "ordering": ["-is_primary_patient", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("SELF", "Self"),
                            ("SPOUSE", "Spouse"),
                            ("PARENT", "Parent"),
                            ("CHILD", "Child"),
                            ("SIBLING", "Sibling"),
                            ("GRANDPARENT", "Grandparent"),
                            ("GRANDCHILD", "Grandchild"),
                            ("UNCLE_AUNT", "Uncle / Aunt"),
                            ("NEPHEW_NIECE", "Nephew / Niece"),
                            ("FRIEND", "Friend"),
                            ("CAREGIVER", "Caregiver"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "alternate_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="family.familyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "db_table": "family_emergency_contacts",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="familyprofile",
            index=models.Index(fields=["user"], name="family_prof_user_id_6132e6_idx"),
        ),
        migrations.AddIndex(
            model_name="familyprofile",
            index=models.Index(
                fields=["is_deleted"], name="family_prof_is_dele_0fdb2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(
                fields=["family_profile", "is_deleted"],
                name="family_memb_family__166be5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(
                fields=["is_primary_patient"], name="family_memb_is_prim_b0c840_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["family_profile", "is_primary"],
                name="family_emer_family__8215f6_idx",
            ),
        ),
    ]
