"""Companions constants."""

STATUS_PENDING_VERIFICATION = 'PENDING_VERIFICATION'
STATUS_ACTIVE = 'ACTIVE'
STATUS_INACTIVE = 'INACTIVE'
STATUS_SUSPENDED = 'SUSPENDED'

COMPANION_STATUS_CHOICES = [
    (STATUS_PENDING_VERIFICATION, 'Pending Verification'),
    (STATUS_ACTIVE, 'Active'),
    (STATUS_INACTIVE, 'Inactive'),
    (STATUS_SUSPENDED, 'Suspended'),
]

AVAILABILITY_AVAILABLE = 'AVAILABLE'
AVAILABILITY_BUSY = 'BUSY'
AVAILABILITY_OFFLINE = 'OFFLINE'

AVAILABILITY_CHOICES = [
    (AVAILABILITY_AVAILABLE, 'Available'),
    (AVAILABILITY_BUSY, 'Busy'),
    (AVAILABILITY_OFFLINE, 'Offline'),
]

SKILL_BASIC_CARE = 'BASIC_CARE'
SKILL_MEDICAL_ASSISTANCE = 'MEDICAL_ASSISTANCE'
SKILL_PHYSIOTHERAPY = 'PHYSIOTHERAPY'
SKILL_NURSING = 'NURSING'
SKILL_ELDERLY_CARE = 'ELDERLY_CARE'
SKILL_CHILD_CARE = 'CHILD_CARE'
SKILL_MENTAL_HEALTH = 'MENTAL_HEALTH'
SKILL_EMERGENCY = 'EMERGENCY'

SKILL_CHOICES = [
    (SKILL_BASIC_CARE, 'Basic Care'),
    (SKILL_MEDICAL_ASSISTANCE, 'Medical Assistance'),
    (SKILL_PHYSIOTHERAPY, 'Physiotherapy'),
    (SKILL_NURSING, 'Nursing'),
    (SKILL_ELDERLY_CARE, 'Elderly Care'),
    (SKILL_CHILD_CARE, 'Child Care'),
    (SKILL_MENTAL_HEALTH, 'Mental Health Support'),
    (SKILL_EMERGENCY, 'Emergency Response'),
]

VEHICLE_NONE = 'NONE'
VEHICLE_BIKE = 'BIKE'
VEHICLE_CAR = 'CAR'
VEHICLE_AUTO = 'AUTO'

VEHICLE_CHOICES = [
    (VEHICLE_NONE, 'None'),
    (VEHICLE_BIKE, 'Bike'),
    (VEHICLE_CAR, 'Car'),
    (VEHICLE_AUTO, 'Auto'),
]
