# Generated by Django 5.0.1 on 2026-07-02 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fence_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup Zone"),
                            ("hospital", "Hospital Zone"),
                            ("drop", "Drop Zone"),
                            ("custom", "Custom Zone"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("radius_meters", models.PositiveIntegerField(default=200)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofences",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geofence",
                "verbose_name_plural": "Geofences",
                "db_table": "geofences",
            },
        ),
        migrations.CreateModel(
            name="GeofenceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("enter", "Enter"), ("exit", "Exit")], max_length=5
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_events",
                        to="bookings.booking",
                    ),
                ),
                (
                    "companion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="live_tracking.geofence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geofence Event",
                "verbose_name_plural": "Geofence Events",
                "db_table": "geofence_events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in meters", null=True
                    ),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, help_text="Speed in km/h", null=True),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True,
                        help_text="Compass heading in degrees (0–360)",
                        null=True,
                    ),
                ),
                ("altitude", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("companion_app", "Companion App"),
                            ("family_app", "Family App"),
                            ("system", "System"),
                        ],
                        default="companion_app",
                        max_length=20,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Device timestamp when GPS fix was taken",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_updates",
                        to="bookings.booking",
                    ),
                ),
                (
                    "companion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Update",
                "verbose_name_plural": "Location Updates",
                "db_table": "location_updates",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leg",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("hospital", "Hospital"),
                            ("drop", "Drop Home"),
                        ],
                        db_index=True,
                        default="pickup",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=15,
                    ),
                ),
                (
                    "origin_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "origin_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("origin_address", models.TextField(blank=True)),
                (
                    "destination_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("destination_address", models.TextField(blank=True)),
                (
                    "polyline",
                    models.TextField(
                        blank=True,
                        help_text="Encoded polyline string (Google Maps format)",
                    ),
                ),
                ("distance_meters", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "db_table": "routes",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="geofence",
            index=models.Index(
                fields=["booking", "fence_type", "is_active"],
                name="geofences_booking_c6e04c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geofenceevent",
            index=models.Index(
                fields=["booking", "occurred_at"], name="geofence_ev_booking_83e0fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geofenceevent",
            index=models.Index(
                fields=["geofence", "event_type"], name="geofence_ev_geofenc_7898ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationupdate",
            index=models.Index(
                fields=["booking", "recorded_at"], name="location_up_booking_cfacd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationupdate",
            index=models.Index(
                fields=["companion", "recorded_at"],
                name="location_up_compani_fa8870_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["booking", "leg", "status"], name="routes_booking_50a93a_idx"
            ),
        ),
    ]
