# Generated by Django 5.0.1 on 2026-07-01 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareJourney",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("PICKUP", "Pickup Patient"),
                            ("HOSPITAL_ARRIVAL", "Hospital Arrival"),
                            ("REGISTRATION", "Registration"),
                            ("CONSULTATION", "Doctor Consultation"),
                            ("LAB_TESTS", "Lab Tests"),
                            ("MEDICINE_PURCHASE", "Medicine Purchase"),
                            ("COLLECT_REPORTS", "Collect Reports"),
                            ("DROP_HOME", "Drop Home"),
                            ("COMPLETED", "Journey Complete"),
                        ],
                        default="PICKUP",
                        max_length=25,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("companion_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_journey",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Care Journey",
                "verbose_name_plural": "Care Journeys",
                "db_table": "care_journeys",
            },
        ),
        migrations.CreateModel(
            name="JourneyStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_code",
                    models.CharField(
                        choices=[
                            ("PICKUP", "Pickup Patient"),
                            ("HOSPITAL_ARRIVAL", "Hospital Arrival"),
                            ("REGISTRATION", "Registration"),
                            ("CONSULTATION", "Doctor Consultation"),
                            ("LAB_TESTS", "Lab Tests"),
                            ("MEDICINE_PURCHASE", "Medicine Purchase"),
                            ("COLLECT_REPORTS", "Collect Reports"),
                            ("DROP_HOME", "Drop Home"),
                            ("COMPLETED", "Journey Complete"),
                        ],
                        max_length=25,
                    ),
                ),
                ("step_order", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="care_journey.carejourney",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Step",
                "verbose_name_plural": "Journey Steps",
                "db_table": "journey_steps",
                "ordering": ["step_order"],
            },
        ),
        migrations.AddIndex(
            model_name="carejourney",
            index=models.Index(fields=["status"], name="care_journe_status_e1336d_idx"),
        ),
        migrations.AddIndex(
            model_name="carejourney",
            index=models.Index(
                fields=["booking"], name="care_journe_booking_9963ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeystep",
            index=models.Index(
                fields=["journey", "step_order"], name="journey_ste_journey_12d15f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journeystep",
            unique_together={("journey", "step_code")},
        ),
    ]
