# Generated by Django 5.0.1 on 2026-07-08 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care_journey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journeystep",
            name="family_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journeystep",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeystep",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carejourney",
            name="current_step",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "Accepted"),
                    ("ON_THE_WAY", "On The Way"),
                    ("REACHED_PATIENT", "Reached Patient"),
                    ("PATIENT_PICKED_UP", "Patient Picked Up"),
                    ("REACHED_HOSPITAL", "Reached Hospital"),
                    ("REGISTRATION_COMPLETED", "Registration Completed"),
                    ("CONSULTATION_STARTED", "Consultation Started"),
                    ("CONSULTATION_COMPLETED", "Consultation Completed"),
                    ("DIAGNOSTIC_TESTS", "Diagnostic Tests"),
                    ("MEDICINE_PURCHASED", "Medicine Purchased"),
                    ("REPORTS_COLLECTED", "Reports Collected"),
                    ("RETURNING_HOME", "Returning Home"),
                    ("JOURNEY_COMPLETED", "Journey Completed"),
                ],
                default="ACCEPTED",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="journeystep",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                ],
                db_index=True,
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="journeystep",
            name="step_code",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "Accepted"),
                    ("ON_THE_WAY", "On The Way"),
                    ("REACHED_PATIENT", "Reached Patient"),
                    ("PATIENT_PICKED_UP", "Patient Picked Up"),
                    ("REACHED_HOSPITAL", "Reached Hospital"),
                    ("REGISTRATION_COMPLETED", "Registration Completed"),
                    ("CONSULTATION_STARTED", "Consultation Started"),
                    ("CONSULTATION_COMPLETED", "Consultation Completed"),
                    ("DIAGNOSTIC_TESTS", "Diagnostic Tests"),
                    ("MEDICINE_PURCHASED", "Medicine Purchased"),
                    ("REPORTS_COLLECTED", "Reports Collected"),
                    ("RETURNING_HOME", "Returning Home"),
                    ("JOURNEY_COMPLETED", "Journey Completed"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="JourneyMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="journey_media/")),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Prescription', 'Bill', 'Report', 'Image'",
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="care_journey.journeystep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Media",
                "verbose_name_plural": "Journey Media",
                "db_table": "journey_media",
            },
        ),
    ]
