"""Bookings constants."""

STATUS_PENDING = 'PENDING'
STATUS_CONFIRMED = 'CONFIRMED'
STATUS_COMPANION_ASSIGNED = 'COMPANION_ASSIGNED'
STATUS_IN_PROGRESS = 'IN_PROGRESS'
STATUS_COMPLETED = 'COMPLETED'
STATUS_CANCELLED = 'CANCELLED'
STATUS_FAILED = 'FAILED'

BOOKING_STATUS_CHOICES = [
    (STATUS_PENDING, 'Pending'),
    (STATUS_CONFIRMED, 'Confirmed'),
    (STATUS_COMPANION_ASSIGNED, 'Companion Assigned'),
    (STATUS_IN_PROGRESS, 'In Progress'),
    (STATUS_COMPLETED, 'Completed'),
    (STATUS_CANCELLED, 'Cancelled'),
    (STATUS_FAILED, 'Failed'),
]

BOOKING_TYPE_SCHEDULED = 'SCHEDULED'
BOOKING_TYPE_INSTANT = 'INSTANT'
BOOKING_TYPE_EMERGENCY = 'EMERGENCY'

BOOKING_TYPE_CHOICES = [
    (BOOKING_TYPE_SCHEDULED, 'Scheduled'),
    (BOOKING_TYPE_INSTANT, 'Instant'),
    (BOOKING_TYPE_EMERGENCY, 'Emergency'),
]

CANCEL_BY_FAMILY = 'FAMILY'
CANCEL_BY_COMPANION = 'COMPANION'
CANCEL_BY_ADMIN = 'ADMIN'
CANCEL_BY_SYSTEM = 'SYSTEM'

CANCEL_BY_CHOICES = [
    (CANCEL_BY_FAMILY, 'Family'),
    (CANCEL_BY_COMPANION, 'Companion'),
    (CANCEL_BY_ADMIN, 'Admin'),
    (CANCEL_BY_SYSTEM, 'System'),
]
