# Generated by Django 5.0.1 on 2026-06-30 08:45

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Unique email address for authentication",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        help_text="Unique phone number with country code",
                        max_length=128,
                        region=None,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("FAMILY", "Family Member"),
                            ("COMPANION", "Care Companion"),
                            ("SUPPORT", "Support Staff"),
                        ],
                        db_index=True,
                        default="FAMILY",
                        help_text="User role in the system",
                        max_length=20,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="First name", max_length=100),
                ),
                ("last_name", models.CharField(help_text="Last name", max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        help_text="Gender",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture",
                        null=True,
                        upload_to="users/profiles/%Y/%m/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short biography", max_length=500
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, help_text="Address line 1", max_length=255
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, help_text="Address line 2", max_length=255
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=100),
                ),
                (
                    "state",
                    models.CharField(blank=True, help_text="State", max_length=100),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="6-digit postal code",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{6}$", "Enter a valid 6-digit postal code"
                            )
                        ],
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="India", help_text="Country", max_length=100
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False, help_text="Email verification status"
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(
                        default=False, help_text="Phone verification status"
                    ),
                ),
                (
                    "is_profile_complete",
                    models.BooleanField(
                        default=False, help_text="Profile completion status"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active status"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, help_text="Staff status"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, help_text="Blocked status"),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(default=True, help_text="Enable notifications"),
                ),
                (
                    "email_notification_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable email notifications"
                    ),
                ),
                (
                    "sms_notification_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable SMS notifications"
                    ),
                ),
                (
                    "push_notification_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable push notifications"
                    ),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        blank=True, help_text="Firebase Cloud Messaging token"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, help_text="Last login timestamp", null=True
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Email verification timestamp", null=True
                    ),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Phone verification timestamp", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        db_index=True, help_text="Type of activity", max_length=50
                    ),
                ),
                ("description", models.TextField(help_text="Activity description")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Activity timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "db_table": "user_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="users_phone_n_a3b1c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "created_at"], name="user_activi_user_id_c742e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type"], name="user_activi_activit_534635_idx"
            ),
        ),
    ]
