# Generated by Django 5.0.1 on 2026-07-01 09:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("family", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("known_allergies", models.TextField(blank=True)),
                ("chronic_conditions", models.TextField(blank=True)),
                ("current_medications", models.TextField(blank=True)),
                ("special_needs", models.TextField(blank=True)),
                ("dietary_restrictions", models.TextField(blank=True)),
                (
                    "mobility_level",
                    models.CharField(
                        choices=[
                            ("INDEPENDENT", "Independent"),
                            ("ASSISTED", "Assisted"),
                            ("WHEELCHAIR", "Wheelchair"),
                            ("BEDRIDDEN", "Bedridden"),
                        ],
                        default="INDEPENDENT",
                        max_length=20,
                    ),
                ),
                ("requires_wheelchair", models.BooleanField(default=False)),
                ("requires_oxygen", models.BooleanField(default=False)),
                ("requires_stretcher", models.BooleanField(default=False)),
                ("emergency_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DECEASED", "Deceased"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary patient for this family account.",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family_member",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to="family.familymember",
                    ),
                ),
                (
                    "family_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="family.familyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "patients",
                "ordering": ["-is_primary", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="PatientInsurance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("GOVERNMENT", "Government"),
                            ("PRIVATE", "Private"),
                            ("CORPORATE", "Corporate"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(blank=True, max_length=200)),
                ("policy_number", models.CharField(blank=True, max_length=100)),
                ("policy_holder_name", models.CharField(blank=True, max_length=200)),
                (
                    "coverage_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coverage amount in INR",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Insurance",
                "verbose_name_plural": "Patient Insurance Records",
                "db_table": "patient_insurance",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientVital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Systolic BP in mmHg",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Diastolic BP in mmHg",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Heart rate in bpm",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Body temperature in °C",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(45),
                        ],
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="SpO2 percentage",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "blood_glucose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Blood glucose in mg/dL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("recorded_by", models.CharField(blank=True, max_length=200)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Vital",
                "verbose_name_plural": "Patient Vitals",
                "db_table": "patient_vitals",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["family_profile", "is_deleted"],
                name="patients_family__d334b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["status"], name="patients_status_7c14f6_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["is_primary"], name="patients_is_prim_9aa136_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientinsurance",
            index=models.Index(
                fields=["patient", "is_active"], name="patient_ins_patient_2b7bf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientvital",
            index=models.Index(
                fields=["patient", "recorded_at"], name="patient_vit_patient_8ad00e_idx"
            ),
        ),
    ]
