# Generated by Django 5.0.1 on 2026-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="preferred_doctor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_hospital_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_hospital_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
