"""Care Journey constants — journey steps matching the main workflow."""

STEP_ACCEPTED = 'ACCEPTED'
STEP_ON_THE_WAY = 'ON_THE_WAY'
STEP_REACHED_PATIENT = 'REACHED_PATIENT'
STEP_PATIENT_PICKED_UP = 'PATIENT_PICKED_UP'
STEP_REACHED_HOSPITAL = 'REACHED_HOSPITAL'
STEP_REGISTRATION_COMPLETED = 'REGISTRATION_COMPLETED'
STEP_CONSULTATION_STARTED = 'CONSULTATION_STARTED'
STEP_CONSULTATION_COMPLETED = 'CONSULTATION_COMPLETED'
STEP_DIAGNOSTIC_TESTS = 'DIAGNOSTIC_TESTS'
STEP_MEDICINE_PURCHASED = 'MEDICINE_PURCHASED'
STEP_REPORTS_COLLECTED = 'REPORTS_COLLECTED'
STEP_RETURNING_HOME = 'RETURNING_HOME'
STEP_JOURNEY_COMPLETED = 'JOURNEY_COMPLETED'

JOURNEY_STEPS = [
    (STEP_ACCEPTED, 'Accepted'),
    (STEP_ON_THE_WAY, 'On The Way'),
    (STEP_REACHED_PATIENT, 'Reached Patient'),
    (STEP_PATIENT_PICKED_UP, 'Patient Picked Up'),
    (STEP_REACHED_HOSPITAL, 'Reached Hospital'),
    (STEP_REGISTRATION_COMPLETED, 'Registration Completed'),
    (STEP_CONSULTATION_STARTED, 'Consultation Started'),
    (STEP_CONSULTATION_COMPLETED, 'Consultation Completed'),
    (STEP_DIAGNOSTIC_TESTS, 'Diagnostic Tests'),
    (STEP_MEDICINE_PURCHASED, 'Medicine Purchased'),
    (STEP_REPORTS_COLLECTED, 'Reports Collected'),
    (STEP_RETURNING_HOME, 'Returning Home'),
    (STEP_JOURNEY_COMPLETED, 'Journey Completed'),
]

STEP_ORDER = [
    STEP_ACCEPTED, STEP_ON_THE_WAY, STEP_REACHED_PATIENT,
    STEP_PATIENT_PICKED_UP, STEP_REACHED_HOSPITAL, STEP_REGISTRATION_COMPLETED,
    STEP_CONSULTATION_STARTED, STEP_CONSULTATION_COMPLETED, STEP_DIAGNOSTIC_TESTS,
    STEP_MEDICINE_PURCHASED, STEP_REPORTS_COLLECTED, STEP_RETURNING_HOME,
    STEP_JOURNEY_COMPLETED,
]

STEP_STATUS_PENDING = 'PENDING'
STEP_STATUS_IN_PROGRESS = 'IN_PROGRESS'
STEP_STATUS_DONE = 'DONE'

STEP_STATUS_CHOICES = [
    (STEP_STATUS_PENDING, 'Pending'),
    (STEP_STATUS_IN_PROGRESS, 'In Progress'),
    (STEP_STATUS_DONE, 'Done'),
]

JOURNEY_STATUS_ACTIVE = 'ACTIVE'
JOURNEY_STATUS_COMPLETED = 'COMPLETED'
JOURNEY_STATUS_CANCELLED = 'CANCELLED'

JOURNEY_STATUS_CHOICES = [
    (JOURNEY_STATUS_ACTIVE, 'Active'),
    (JOURNEY_STATUS_COMPLETED, 'Completed'),
    (JOURNEY_STATUS_CANCELLED, 'Cancelled'),
]
