# Generated by Django 5.0.1 on 2026-07-03 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("operations", "Operations"),
                            ("revenue", "Revenue"),
                            ("users", "Users"),
                            ("quality", "Quality"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=10,
                    ),
                ),
                ("metric_name", models.CharField(blank=True, max_length=100)),
                (
                    "metric_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "analytics_insights",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "severity"],
                        name="analytics_i_is_acti_283728_idx",
                    ),
                    models.Index(
                        fields=["category", "generated_at"],
                        name="analytics_i_categor_e01afd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user_registered", "User Registered"),
                            ("booking_created", "Booking Created"),
                            ("booking_completed", "Booking Completed"),
                            ("payment_completed", "Payment Completed"),
                            ("api_request", "API Request"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="analytics_e_event_t_7b4dc8_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="analytics_e_entity__5128ee_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("bookings", "Bookings"),
                            ("revenue", "Revenue"),
                            ("user_growth", "User Growth"),
                            ("companion_performance", "Companion Performance"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "status"],
                        name="analytics_r_report__766651_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "created_at"],
                        name="analytics_r_request_225a0e_idx",
                    ),
                ],
            },
        ),
    ]
