# Generated by Django 5.0.1 on 2026-07-03 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("companion_match", "Companion Match"),
                            ("medical_summary", "Medical Summary"),
                            ("trust_score", "Trust Score"),
                            ("priority", "Priority Assessment"),
                            ("reminder", "Care Reminder"),
                            ("chat", "AI Chat"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("output_data", models.JSONField(default=dict)),
                (
                    "model_used",
                    models.CharField(blank=True, default="rule_based", max_length=100),
                ),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="ai_engine.airequest",
                    ),
                ),
            ],
            options={
                "db_table": "ai_responses",
            },
        ),
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "rating_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "skills_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "experience_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "trust_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "availability_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "companion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="companions.companionprofile",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="ai_engine.airequest",
                    ),
                ),
            ],
            options={
                "db_table": "ai_match_scores",
                "ordering": ["rank"],
            },
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["user", "request_type"], name="ai_requests_user_id_a8ca49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["status", "created_at"], name="ai_requests_status_bb25fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["request", "rank"], name="ai_match_sc_request_349415_idx"
            ),
        ),
    ]
