# Generated by Django 5.0.1 on 2026-06-30 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INVALID_CREDENTIALS", "Invalid Credentials"),
                            ("USER_NOT_FOUND", "User Not Found"),
                            ("USER_BLOCKED", "User Blocked"),
                            ("USER_INACTIVE", "User Inactive"),
                            ("EMAIL_NOT_VERIFIED", "Email Not Verified"),
                            ("PHONE_NOT_VERIFIED", "Phone Not Verified"),
                            ("TOO_MANY_ATTEMPTS", "Too Many Attempts"),
                            ("OTP_REQUIRED", "OTP Required"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_data",
                    models.JSONField(
                        blank=True, help_text="Geolocation data", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "authentication_login_attempts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "created_at"],
                        name="authenticat_user_id_33ca37_idx",
                    ),
                    models.Index(
                        fields=["email", "created_at"],
                        name="authenticat_email_d7d955_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="authenticat_ip_addr_d6fb1d_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="authenticat_status_bd634c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                (
                    "otp_type",
                    models.CharField(
                        choices=[
                            ("EMAIL_VERIFICATION", "Email Verification"),
                            ("PHONE_VERIFICATION", "Phone Verification"),
                            ("LOGIN", "Login"),
                            ("PASSWORD_RESET", "Password Reset"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "authentication_otps",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "otp_type", "is_verified"],
                        name="authenticat_user_id_286002_idx",
                    ),
                    models.Index(
                        fields=["otp_code", "expires_at"],
                        name="authenticat_otp_cod_e5a2ec_idx",
                    ),
                    models.Index(
                        fields=["email", "otp_type"],
                        name="authenticat_email_1a1e01_idx",
                    ),
                    models.Index(
                        fields=["phone_number", "otp_type"],
                        name="authenticat_phone_n_2ab358_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "authentication_password_reset_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token", "is_used"], name="authenticat_token_5b0eb6_idx"
                    ),
                    models.Index(
                        fields=["user", "expires_at"],
                        name="authenticat_user_id_df6264_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.TextField(unique=True)),
                (
                    "jti",
                    models.CharField(help_text="JWT ID", max_length=255, unique=True),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "authentication_refresh_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_revoked"],
                        name="authenticat_user_id_68e256_idx",
                    ),
                    models.Index(
                        fields=["jti", "is_revoked"], name="authenticat_jti_6f1b2d_idx"
                    ),
                    models.Index(fields=["token"], name="authenticat_token_79644a_idx"),
                    models.Index(
                        fields=["device_id", "user"],
                        name="authenticat_device__9a4937_idx",
                    ),
                ],
            },
        ),
    ]
